name: Publish GitHub Release Notes

on:
  push:
    tags:
      - "v*"

jobs:
  release_version:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Generate Release Notes from Changelog
        uses: lsegal/github-release-from-changelog-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
